# Generated by Django 3.1.5 on 2021-02-02 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 12, 28, 39, 936613)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 12, 28, 39, 928489)),
        ),
    ]
