# Generated by Django 3.1.5 on 2021-02-02 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0002_auto_20210202_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 17, 1, 47, 380774)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 17, 1, 47, 380774)),
        ),
    ]
