# Generated by Django 3.1.5 on 2021-02-02 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0003_auto_20210202_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 18, 23, 35, 512614)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 2, 18, 23, 35, 512614)),
        ),
    ]
