# Generated by Django 3.1.5 on 2021-02-04 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0004_auto_20210202_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 4, 18, 15, 44, 546475)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 4, 18, 15, 44, 546475)),
        ),
    ]
