# Generated by Django 3.1.5 on 2021-02-04 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0005_auto_20210204_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='price',
            field=models.IntegerField(default=3.9),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 4, 18, 33, 14, 41142)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 4, 18, 33, 14, 41142)),
        ),
    ]
