# Generated by Django 3.1.5 on 2021-02-05 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rented', '0006_auto_20210204_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='price',
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 5, 11, 9, 58, 140540)),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_start',
            field=models.DateField(verbose_name=datetime.datetime(2021, 2, 5, 11, 9, 58, 140540)),
        ),
    ]
