# Generated by Django 3.1.5 on 2021-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('year', models.IntegerField(default=2000)),
                ('director', models.CharField(default='awaiting director', max_length=80)),
                ('genre', models.CharField(default='awaiting genre', max_length=30)),
                ('description', models.TextField(default='awaiting description')),
                ('imdb_score', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
