# Generated by Django 3.1.5 on 2021-01-30 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        
        ('moviestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
            preserve_default=False,
        ),
    ]
