# Generated by Django 3.1.5 on 2021-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0002_movie_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.FloatField(default=0.0),
        ),
    ]
