# Generated by Django 3.1.5 on 2021-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0003_auto_20210130_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%d/%m/%Y/'),
        ),
    ]
