# Generated by Django 3.1.5 on 2021-01-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0005_auto_20210130_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='client',
            new_name='user',
        ),
    ]
