# Generated by Django 3.1.5 on 2021-02-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviestore', '0006_auto_20210131_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.FloatField(default=3.9),
        ),
        migrations.AddField(
            model_name='movie',
            name='quantity_stock',
            field=models.IntegerField(default=10),
        ),
    ]
